applications:
  documentation-impact-analyzer:
    type: php:8.3

    build:
      flavor: none

    hooks:
      build: |
        set -xe
        composer install --no-progress --no-interaction --optimize-autoloader --no-dev
      deploy: |
        set -xe

    web:
      locations:
        /:
          root: public
          passthru: /index.php
          expires: 5m

    runtime:
      extensions:
        - pdo_pgsql
        - zip

    mounts:
      var/cache:
        source: tmp
      var/log:
        source: storage

    variables:
      php:
        opcache.preload: config/preload.php

routes:
  "https://{default}/":
    type: upstream
    upstream: documentation-impact-analyzer:http
