monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: info
            formatter: monolog.formatter.json

        file:
            type: stream
            path: "%kernel.project_dir%/var/log/webhook.log"
            level: info
