# config/packages/prod/monolog.yaml
monolog:
    handlers:
        nested:
            type: stream
            path: php://stderr
            level: debug
        buffer:
            type: buffer

        syslog_handler:
            type: syslog
            # log error-level messages and higher
            level: error
