# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.max_diff_size: 50000

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    
    # Git provider services
    App\Service\GitLabService:
        arguments:
            $apiToken: '%env(GITLAB_TOKEN)%'
            $webhookSecret: '%env(GITLAB_WEBHOOK_SECRET)%'

    App\Service\GitHubService:
        arguments:
            $apiToken: '%env(GITHUB_TOKEN)%'
            $webhookSecret: '%env(GITHUB_WEBHOOK_SECRET)%'

    # Documentation analyzer
    App\Service\DocumentationAnalyzer:
        arguments:
            $openaiApiKey: '%env(OPENAI_API_KEY)%'
            $maxDiffSize: '%app.max_diff_size%'

    # Alias for GitLab provider
    App\Service\GitProviderInterface $gitLabProvider: '@App\Service\GitLabService'
    
    # Alias for GitHub provider  
    App\Service\GitProviderInterface $gitHubProvider: '@App\Service\GitHubService'
